# Generated by Django 4.2 on 2026-04-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Secretariat', 'Secrétariat'), ('Comptable', 'Comptable'), ('Dirigeant', 'Dirigeant'), ('Enseignant', 'Enseignant'), ('Etudiant', 'Étudiant'), ('Parent', 'Parent')], default='Secretariat', max_length=20),
        ),
    ]
